/**
 * Created by ximing on 12/28/17.
 */
'use strict';
export const OP_NAME = {
    VALUE: 'OP_VALUE',
    ADD_MARK: 'OP_ADD_MARK',
    ClEAR_MARK: 'OP_CLEAR_MARK',
    REMOVE_MARK: 'OP_REMOVE_MARK',
    SET_FORMULA: 'OP_SET_FORMULA',
    SET_FMT: 'OP_SET_FMT',
    SET_SHEET_SETTING: 'OP_SHEET_SETTING',
    SWITCH_SHEET: 'OP_SWITCH_SHEET',
    CHANGE_SHEET: 'OP_CHANGE_SHEET',
    ADD_SHEET: 'OP_ADD_SHEET',
    REMOVE_SHEET: 'OP_REMOVE_SHEET',
    CHANGE_SELECTION: 'OP_CHANGE_SELECTION'
};
